name: marketc
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3 # Lightweight and blazing fast key-value database written in pure Dart.
  hive_flutter: ^1.1.0 # Extension for Hive. Makes it easier to use Hive in Flutter apps

  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1 # For creating cubit states
  json_annotation: ^4.8.1 # Classes and helper functions that support JSON code generation

  # Service locator
  get_it: ^7.6.4
  get: ^4.6.6

  # Multiple Language Support
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0 # internationalized/localized code formatting

  # Handling Hardware Permissions
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.2

  # Comparing Dart Objects
  equatable: ^2.0.5

  # Adding Functional Programming
  dartz: ^0.10.1

  # Connecting to the API
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1 # Better visualization for API response

  # FireBase
  firebase_core: ^2.24.2 # Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps.
  firebase_messaging: ^14.7.10 # Flutter plugin for Firebase Cloud Messaging

  # Ui Fonts & Icons
  google_fonts: ^6.1.0 # Fonts
  material_design_icons_flutter: ^7.0.7296 # Material icons made by community

  # Ui Widgets
  getwidget: ^4.0.0
  gap: ^3.0.1 # Better SizedBoxes
  cached_network_image: ^3.2.3 # Saving images for offline use
  pinput: ^3.0.1 # Adding verification code fields
  conditional_builder_null_safety: ^0.0.6 # Show UI elements according to conditional type
  flutter_native_splash: ^2.3.0 # Customize Flutter's default white native splash screen with background color and splash image
  flutter_launcher_icons: ^0.13.1 # A package which simplifies the task of updating your Flutter app's launcher icon
  flutter_svg: ^2.0.9 # An SVG rendering and widget library for Flutter
  smooth_page_indicator: ^1.1.0
  country_code_picker: ^3.0.0
  dotted_border: ^2.1.0 # A flutter package to let users easily add a dashed border around any widget
  flutter_html:
  auto_height_grid_view: ^1.0.0
  roundcheckbox: ^2.0.5
  auto_size_text: ^3.0.0

  # Flutter plugin for adapting screen and font size.
  flutter_screenutil: ^5.9.0

  change_app_package_name: ^1.1.0 # Change App Package Name with single command
  flutter_timer_countdown: ^1.0.7
  uuid: ^4.3.3 # Generate a v4 (random) id
  file_picker: ^6.1.1 # A package that allows you to use a native file explorer to pick single or multiple absolute file paths, with extension filtering support.
  image_picker: ^1.0.7 # Flutter plugin for selecting images from the Android and iOS image library, and taking new pictures with the camera.

  # Maps
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Readex Pro
      fonts:
        - asset: assets/fonts/ReadexPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/ReadexPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ReadexPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/ReadexPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/ReadexPro-Light.ttf
          weight: 300
        - asset: assets/fonts/ReadexPro-ExtraLight.ttf
          weight: 200
    - family: Abhaya Libre
      fonts:
        - asset: assets/fonts/AbhayaLibre-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AbhayaLibre-Bold.ttf
          weight: 700
        - asset: assets/fonts/AbhayaLibre-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AbhayaLibre-Medium.ttf
          weight: 500
        - asset: assets/fonts/AbhayaLibre-Regular.ttf
          weight: 400
